In [2]:
import pandas as pd 
# DataFrame con información de empleados 
data_empleados = { 
'id_empleado': [101, 102, 103, 104, 105, 106, 107, 108], 
'nombre': ['Ana', 'Luis', 'Sofía', 'Carlos', 'Elena', 'Pedro', 'Laura', 
'David'], 
'salario': [55000, 58000, 72000, 48000, 75000, 85000, 62000, 88000], 
'id_departamento': ['V_01', 'V_01', 'T_01', 'M_01', 'T_01', 'D_01', 
'M_01', 'D_01'] 
} 
df_empleados = pd.DataFrame(data_empleados) 
# DataFrame con información de departamentos 
data_departamentos = { 
'id_departamento': ['V_01', 'T_01', 'M_01', 'D_01'], 
'nombre_depto': ['Ventas', 'Tecnología', 'Marketing', 'Dirección'], 'ubicacion': ['Norte', 'Sur', 'Norte', 'Norte'] 
} 
df_departamentos = pd.DataFrame(data_departamentos)

In [3]:
# Combinacion de datos
df_completo = pd.merge(
    df_empleados,
    df_departamentos,
    on='id_departamento',
    how='inner'
)

display(df_completo)

   id_empleado  nombre  salario id_departamento nombre_depto ubicacion
0          101     Ana    55000            V_01       Ventas     Norte
1          102    Luis    58000            V_01       Ventas     Norte
2          103   Sofía    72000            T_01   Tecnología       Sur
3          104  Carlos    48000            M_01    Marketing     Norte
4          105   Elena    75000            T_01   Tecnología       Sur
5          106   Pedro    85000            D_01    Dirección     Norte
6          107   Laura    62000            M_01    Marketing     Norte
7          108   David    88000            D_01    Dirección     Norte

In [4]:
# Agrupamiento y agregacion
salario_promedio = (
    df_completo
    .groupby(['nombre_depto', 'ubicacion'], as_index=False)['salario']
    .mean()
    .rename(columns={'salario': 'salario_promedio'})
)

display(salario_promedio)

  nombre_depto ubicacion  salario_promedio
0    Dirección     Norte           86500.0
1    Marketing     Norte           55000.0
2   Tecnología       Sur           73500.0
3       Ventas     Norte           56500.0

In [5]:
# Pivoteo de datos
tabla_pivote = salario_promedio.pivot(
    index='nombre_depto',
    columns='ubicacion',
    values='salario_promedio'
)

display(tabla_pivote)

ubicacion       Norte      Sur
nombre_depto
Dirección     86500.0      NaN
Marketing     55000.0      NaN
Tecnología        NaN  73500.0
Ventas        56500.0      NaN